[general]
log_level = "info"

[provider]
class = "Smartsim"
device = "CPU"
model_backend = "TORCH"
model_path = "/hpcwork/ro092286/smartsim/mini_app/train_models/best_model_field_jit_watercnn.pt"
model_name = "watercnn"


[normalization]
class="minmax"
input_min=-1.0
input_max=1.0
output_min=0.0
output_max=1.0

[behavior]
class="periodic"
inference_interval = 50
coupled_steps_before_inference = 6
coupled_steps_stride = 1
step_increment_after_inference = 24

[application]
class="MLCouplingApplicationTurbulenceClosure"